---
on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump_tag.outputs.tag }}
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: release
          RELEASE_BRANCHES: testing, release
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ steps.bump_tag.outputs.tag }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  release_testing_html:
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: index.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: ld54
          ITCH_USER: chewiecb
          PACKAGE: index.zip
          VERSION: ${{ steps.download-html.outputs.version }}
  notify-discord:
    runs-on: ubuntu-latest
    needs: [export_game, release_testing_html]
    steps:
      - name: get tagged release
        id: get-tagged-release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.export_game.outputs.tag }}
      - name: notify discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: BuildBot
          description: '${{ steps.get-tagged-release.outputs.body }}' 
          footer: ${{ needs.export_game.outputs.tag }}
          text: A new build is available at https://chewiecb.itch.io/ld54
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}