---
on:
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump_tag.outputs.tag }}
    name: Export game to Github
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
          PRERELEASE_SUFFIX: alpha
          DEFAULT_BRANCH: release
          RELEASE_BRANCHES: testing, release
    
      - name: 'Get new tag'
        id: new_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Overwrite version in 'build_tag.cfg' and push changes
        run: |
          echo "${{ steps.new_tag.outputs.tag }}" > 'build_tag.cfg'
      
      - name: Checkout with updated build tag
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Export game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ steps.bump_tag.outputs.tag }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  release_testing_html:
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: index.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: ld54-test
          ITCH_USER: chewiecb
          PACKAGE: index.zip
          VERSION: ${{ steps.download-html.outputs.version }}
  release_testing_windows:
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: Download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: ld54_windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ld54-test
          ITCH_USER: chewiecb
          PACKAGE: ld54_windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_testing_linux:
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: Download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: ld54_linux.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ld54-test
          ITCH_USER: chewiecb
          PACKAGE: ld54_linux.zip
          VERSION: ${{ steps.download-linux.outputs.version }}
  notify-discord:
    runs-on: ubuntu-latest
    needs: [export_game, release_testing_html, release_testing_windows, release_testing_linux]
    steps:
      - name: get tagged release
        id: get-tagged-release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.export_game.outputs.tag }}
      - name: notify discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          username: BuildBot
          description: '${{ steps.get-tagged-release.outputs.body }}' 
          details: '__This is a pre-release build and may be unstable__'
          footer: ${{ needs.export_game.outputs.tag }}
          text: A new __testing__ build is available at https://chewiecb.itch.io/ld54-tb
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
